export const LOAD_CART = "LOAD_CART"
export const ADD_TO_CART = "ADD_TO_CART"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const QUANTITY_INCREASE = "QUANTITY_INCREASE"
export const QUANTITY_DECREASE = "QUANTITY_DECREASE"

export const BUY = "BUY"